imagehash.settings:
  type: config_object
  label: 'Image File Hash settings'
  mapping:
    algos:
      type: mapping
      label: 'Enabled image hash algorithms'
      mapping:
        difference:
          type: string
          label: 'Difference Image Hash'
        average:
          type: string
          label: 'Average Image Hash'
        block:
          type: string
          label: 'Block Image Hash (experimental)'
        perceptual:
          type: string
          label: 'Perceptual Image Hash (experimental)'

field.formatter.settings.imagehash_table:
  type: mapping
  label: 'Image File Hash table field display format settings'
  mapping:
    algo:
      type: string
      label: 'Image Hash algorithm'
    use_description_as_link_text:
      type: boolean
      label: 'Replace the file name by its description when available'
